<a href="https://colab.research.google.com/github/devendrapandey2005/DSA-with-python/blob/main/7th_sem_python_aur_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''write a program to input electrcity unit charges and calculate total electrcity bill
according to the given condition:

For first 50 units Rs. 0.50/unit

For next 150 units Rs. 0.75/unit

For next 250 units Rs. 1.20/unit

For unit above 450 Rs. 1.50/unit

An additional surcharge of 20% is added to the bill'''
units = float(input("Enter the number of electricity units consumed: "))
bill = 0
if units <= 50:
    bill = units * 0.50
elif units <=200:
  bill = 50*0.50+(units-50)*0.75
elif units <=450 :
  bill = 50*0.5+150*0.75+250*1.50+(units-450)*1.50



Enter the number of electricity units consumed: 5


In [ ]:
'''wap to print if number is divisible by 3 print fizz , number is divisible by 5 print buzz number is divisible by both 3,5 then print fizz and buzz'''
for i in range (1,21):
  if i%3 == 0 and i%5 ==0:
    print("fizz and buzz")
  elif i%3 == 0:
    print("fizz")
  elif i%5 == 0:
    print("buzz")
  else :
    print(i)

1
2
fizz
4
buzz
fizz
7
8
fizz
buzz
11
fizz
13
14
fizz and buzz
16
17
fizz
19
buzz


In [ ]:
'''wap which will print multiplication of all the even and odd the factor'''
num = int(input("enter the number = "))
even_factor = 1
odd_factor = 1
for i in range(1,num+1):
  if num%i == 0:
    if i%2 == 0:
      even_factor*=i
    else:
      odd_factor*=i
print(even_factor,odd_factor)


enter the number = 25
1 125


In [ ]:
'''determine the season based on month
3 <=month <=5; "spring "
6 <=month <=8; "summer"
9 <=month <=11; "autumn"
otherwise
winter'''
month = int(input("Enter the month (1-12): "))

if 3 <= month <= 5:
    season = "spring"
elif 6 <= month <= 8:
    season = "summer"
elif 9 <= month <= 11:
    season = "autumn"
else:
    season = "winter"

print(f"The season for month {month} is {season}")

Enter the month (1-12): 25
The season for month 25 is winter


In [ ]:
'''Write a python program which accept the kilometres covered and calculate the bill according to the following criteria:

First 10 Km > Rs11/km

Next 90Km Rs 10/km

After that > Rs9/km'''
kilometers = float(input("Enter the kilometers covered: "))
bill = 0

if kilometers <= 10:
    bill = kilometers * 11
elif kilometers <= 100:  # 10 + 90 = 100
    bill = (10 * 11) + ((kilometers - 10) * 10)
else:
    bill = (10 * 11) + (90 * 10) + ((kilometers - 100) * 9)

print(f"The total bill is Rs {bill:.2f}")

Enter the kilometers covered: 5
The total bill is Rs 55.00


In [ ]:
n = 1
while n<=19:
  print(n)
  n+=2


1
3
5
7
9
11
13
15
17
19


In [ ]:
''' wap take number from user and print all the factor of the number'''
'''num = int(input("Enter a number: "))

print(f"The factors of {num} are:")
for i in range(1, num + 1):
    if num % i == 0:
        print(i)'''
num = int(input("Enter a number: "))
i = 1
while i<=n:
  if n%i==0:
    print(i,end=" ")
  i+=1

Enter a number: 36
1 3 7 21 

In [ ]:
# Sum of given digits
n = int(input("Enter the number: "))
temp = 0
while n != 0:
    r = n % 10
    temp += r
    n = n // 10  # Fix: added assignment
print("Sum of digits =", temp)

Enter the number: 36
Sum of digits = 9


In [ ]:
# Sum of given digits
n = int(input("Enter the number: "))
temp = 0
while n != 0:
    r = n % 10
    temp += r
    n = n // 10  # Fix: added assignment
print("Sum of digits =", temp)

Enter the number: 36
Sum of digits = 9


In [ ]:
# revrse the number
n = int(input("Enter the number: "))
temp = 0
while n != 0:
    r = n % 10
    temp*=10
    temp += r
    n = n // 10  # Fix: added assignment
print("Sum of digits =", temp)

Enter the number: 363
Sum of digits = 363


In [ ]:
# revrse the number
n = int(input("Enter the number: "))
n1= n
temp = 0
while n != 0:
    r = n % 10
    temp*=10
    temp += r
    n = n // 10
if n1 == temp:
  print("palindrom")
else:
  print("not palindrom")

Enter the number: 36
not palindrom


In [ ]:
'''wap which will take number from user and check number is narcissistic number'''
n = int(input("Enter the number: "))
n1= n
temp = 0
while n != 0:
    r = n % 10
    temp*=10
    temp += r
    n = n // 10
if n1 == temp:
  print("palindrom")
else:
  print("not palindrom")

Enter the number: 36
not palindrom


#LIST
CREATE,
UPDATE,
DELETE,
READ






In [ ]:
X = [1,2,3,4,5,6,7,8,9,10]
print(type(X))

<class 'list'>


In [ ]:
fruits  = [ "apple", "bannana","cherry","kiwi","guvava"]
print(fruits)
fruits[2] = 'watermalon'
print(fruits)
fruits.append("lala")
print(fruits)

['apple', 'bannana', 'cherry', 'kiwi', 'guvava']
['apple', 'bannana', 'watermalon', 'kiwi', 'guvava']
['apple', 'bannana', 'watermalon', 'kiwi', 'guvava', 'lala']


In [ ]:
fruits  = [ "apple", "bannana","cherry","kiwi","guvava"]
fruits.insert(-3,"watermalon")
print(fruits)

['apple', 'bannana', 'watermalon', 'cherry', 'kiwi', 'guvava']


In [ ]:
lst = ['one','two','three','four']
del lst[1]
print(lst)

['one', 'three', 'four']


In [ ]:
lst = ['one','two','three','four','five']
a = lst.pop(3)
print(lst)
print(a)

['one', 'two', 'three', 'five']
four


In [ ]:
lst = [1,2,3,4,5,6,7,8,9,1,0,77,89,44,'jiii']
print(lst)
lst.remove("jiii")
print(lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 0, 77, 89, 44, 'jiii']
[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 0, 77, 89, 44]


In [ ]:
lst = [1,2,[1,1],3,4,5,6]
print(lst)
lst.remove(1)
print(lst)

[1, 2, [1, 1], 3, 4, 5, 6]
[2, [1, 1], 3, 4, 5, 6]


In [ ]:
numbers = [1,2,3,4,5,6,4,5,6]
print(numbers.count(4))

2


In [ ]:
num = [1,2,3,4,5,6,7,8,9,0]
num.reverse()
print(num)

[0, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [ ]:
#through slicing
num = [1,2,3,4,5,6,7,8,9,0]
num[::-1]
print(num)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]


In [ ]:
lst = [2,5,'apple',2]
lst.index(2)

0

In [ ]:
num = [11,12,13,14,15,16,17,20]
for i in range(len(num)):
  print(num)

[11, 12, 13, 14, 15, 16, 17, 20]
[11, 12, 13, 14, 15, 16, 17, 20]
[11, 12, 13, 14, 15, 16, 17, 20]
[11, 12, 13, 14, 15, 16, 17, 20]
[11, 12, 13, 14, 15, 16, 17, 20]
[11, 12, 13, 14, 15, 16, 17, 20]
[11, 12, 13, 14, 15, 16, 17, 20]
[11, 12, 13, 14, 15, 16, 17, 20]


In [ ]:

lst = [1,2,3,4,5,6,7,8,9,10]
even = odd = 0
for i in range(len(lst)):
  if i%2==0:
    print('number is even',i)
  else:
    print('odd number',i)

number is even 0
odd number 1
number is even 2
odd number 3
number is even 4
odd number 5
number is even 6
odd number 7
number is even 8
odd number 9


In [ ]:
#count of even number in given list
lst = [1,2,3,4,5,6,7,8,9,10]
even = odd = 0
for i in range(len(lst)):
  if lst[i]%2==0:
    even+=1
  else:
    odd+=1
print(even,odd)

5 5


In [ ]:
#wap which will take list as a input form user and +5 in even number and -3 in odd number
lst = [1,2,3,4,5,6,7,8,9,10]
print(lst)
even = odd = 0
for i in range(len(lst)):
  if lst[i]%2==0:
    lst[i]+=5
  else:
    lst[i]-=3
print(lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[-2, 7, 0, 9, 2, 11, 4, 13, 6, 15]


In [ ]:
#wap which will take list as a input form user and +5 in even number and -3 in odd number
user_input = input("Enter the list of numbers separated by space: ")
lst = list(map(int, user_input.split()))

# Display the original list
print("Original list:", lst)

# Process the list: +5 to even numbers, -3 to odd numbers
for i in range(len(lst)):
    if lst[i] % 2 == 0:
        lst[i] += 5
    else:
        lst[i] -= 3

# Display the modified list
print("Modified list:", lst)


Enter the list of numbers separated by space: 36
Original list: [36]
Modified list: [41]


In [ ]:
lst = [3,5,7,9,2,8,11,15,12,14]
#output = [5,3,9,7,8,2,15,11,14,12]
for i in range(0, len(lst)-1,2):
  lst[i],lst[i+1] = lst[i+1] , lst[i]
print(lst)

[5, 3, 9, 7, 8, 2, 15, 11, 14, 12]


In [ ]:
#wap which print the largest element of the list
lst = [3,5,7,9,2,8,11,15,12,14]
print(max(lst))

15


In [ ]:
##wap which print the largest element of the list
lst = [3,5,7,9,2,8,11,15,12,14]
temp = lst[0]#this is the index number
for i in range(len(lst)):
  if lst[i]>temp:
    temp=lst[i]
print(temp)

15


In [ ]:
lst = [3,5,7,9,2,8,11,15,12,14]
max1 = lst[1]
max2 = lst[0]
for i in range(2,len(lst)):
  if lst[i]>max1:
    max2=max1
    max1=lst[i]
  elif lst[i]>max2:
    max2=lst[i]
print("second largest number is",max2)

second largest number is 14


In [ ]:
lst = [ 25,3,2,20,8,15,6,12,10]
lst.reverse()
lst1 = [lst[0]]
temp =lst[0]
for i in lst:
  if i>temp:
    temp=i
    lst1.append(temp)
print(lst1)
lst1.reverse()
print(lst1)

[10, 12, 15, 20, 25]
[25, 20, 15, 12, 10]


In [ ]:
lst = [3,5,7,2,8,9]
lst1 = []
for i in lst:
  lst1.append(i**2)
print(lst1)

[9, 25, 49, 4, 64, 81]


In [ ]:
#List comprihansion
lst = [3,5,7,2,8,9]
lst1 = [i**2 for i in lst]
print(lst1)

[9, 25, 49, 4, 64, 81]


In [ ]:
lst  = [3,5,-7,-8,12,-78,-89,78,-77]
lst1 = [i for i in lst if i >0]
lst2 = [i for i in lst if i <0]
print(lst1,lst2)

[3, 5, 12, 78] [-7, -8, -78, -89, -77]


In [ ]:
lst = [1,2,3,4,5,6,7,8,9,10]
lst1 = [i for i in lst if i%2 == 0]
print("even number = ",lst1)
lst2 = [i for i in lst if i%2 != 0]
print("odd number = ",lst2)

even number =  [2, 4, 6, 8, 10]
odd number =  [1, 3, 5, 7, 9]


sort function

In [ ]:
lst = [1,2,3,4,5,6,7,8,9,10]
lst.sort(reverse = True)
print(lst)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [ ]:
lst = [1,2,3,4,5,8,7,8,9,10]
x = sorted(lst)
print(x)
print(lst)

[1, 2, 3, 4, 5, 7, 8, 8, 9, 10]
[1, 2, 3, 4, 5, 8, 7, 8, 9, 10]


In [ ]:
lst = [[3,5,7,9],[8,2,5,9],[7,3,5,8],[8,3,2]]
op_lst = []
for i in lst:
  op_lst.append(max(i))
print(op_lst)

[9, 9, 8, 8]


In [ ]:
lst = [[3,5,7,9],[8,2,5,9],[7,3,5,8],[8,3,2]]
odd_sums = []
for i in lst:
  sum = 0
  for number in i:
    if number % 2 != 0:
      sum += number
  odd_sums.append(sum)

print(odd_sums)

[24, 14, 15, 3]


In [ ]:
lst = [[1,2,3,4],[5,6,7,8],[9,10,11,12,13],[14,15,16,17]]
for i in range(0,len(lst)-1,2):
  for j in range(0,len(lst[i])-1,2):
    lst[i][j],lst[i+1][j]= lst[i+1][j],lst[i][j]
print(lst)

[[5, 2, 7, 4], [1, 6, 3, 8], [14, 10, 16, 12, 13], [9, 15, 11, 17]]


In [ ]:
tpl = ()
tpl1 = tuple()
tpl2 = ('jai hoo',1,2,3,4)
print(tpl,tpl1,tpl2)

() () ('jai hoo', 1, 2, 3, 4)


In [ ]:
tpl = (1,2,3,4,5,66,7,8,9)
print(tpl)

(1, 2, 3, 4, 5, 66, 7, 8, 9)


In [ ]:
tpl = (1,2,3,4,5,66,7,8,9)
print(id(tpl))
tpl+=(21,22,23,25)
print(id(tpl))

132035458952080
132035421379248


In [ ]:
print(dir(tpl))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']


In [ ]:
tpl=[21,22,23,25]
print(tuple(tpl))

(21, 22, 23, 25)


In [ ]:
x = "let's learn python"
print(x[: : -3])
print(x[7 :: 4])
print(x[10 :])
print(x[: : 3])
print(x[-3: -10 :-5])
print(x[-2:])

nt a t
e h
n python
l'lrph
hn
on


In [ ]:
print("o" in "hello world")

True


In [ ]:
x = "PYHTON"
y = x.lower()
print(x)
print(y)

PYHTON
pyhton


In [ ]:
x = "python"
y = x.upper()
print(x)
print(y)

python
PYTHON


In [ ]:
str = "hello user how are you"
lst= str.split()
print(lst)

['hello', 'user', 'how', 'are', 'you']


In [ ]:
str = "0001-0003-0008"
lst= str.split(sep='-')
print(lst)

['0001', '0003', '0008']


In [ ]:
lst = ['0001','0002','0003']
str = " ".join(lst)
print(str)

0001 0002 0003


In [ ]:
date_str = input("enter the date (dd/mm/yyyy): ")
print(date_str)
new_date = date_str.split(sep = "/")
day = new_date[0]
month = new_date[1]
year  = new_date[2]
print("day",day)
print("month",month)
print("year",year)

enter the date (dd/mm/yyyy): 3/5/2025
3/5/2025
day 3
month 5
year 2025


In [ ]:
str1 = "hello everyone let's learn python"
lst = str1.split()
word = ""
for i in range(len(lst)):
  if len(lst[i])>len(word):
    word = lst[i]
print(word,len(word))

everyone 8


In [ ]:
str = input("enter the string = ")
if str == str[: : -1]:
  print("palindrom")
else:
  print("not palindrom")

enter the string = papa
not palindrom


In [ ]:
text = "hello ,everyone. let's, learn. python"
text = text.replace(".",",")
text = text.replace(",","#")
text = text.replace("#",".")
print(text)

hello .everyone. let's. learn. python


set yeh mutable hota hai , set apne andar imuteable veriable store krta hai, set unorder hota , set{} use krte hai , set muteable isliye kyunki hum usmein value add kr skte hai aur existing value ko delete kr skte hai


In [ ]:
st ={}
st = set()
st = {}

In [ ]:
s = set()
print(type(s))

<class 'set'>


In [ ]:
#without element ye {} dictonaryu create krega aur ek bhi value dedo toh yeh set ban jata hai
st = {}
print(type(st))

<class 'dict'>


In [ ]:
s = {1,2}
s.add(3)
print(s)

{1, 2, 3}


In [ ]:
st = {1,2,3}
st.update([1,2,3,4,5,6])
print(st)

{1, 2, 3, 4, 5, 6}


In [ ]:
st = {1,2,3}
st.remove(3)
print(st)

{1, 2}


In [ ]:
st = {1,2,3}
a=st.pop()
print(a)
print(st)

1
{2, 3}


In [ ]:
st = {1,2,3}
print(s)
s.clear()
print(S)

{1, 2, 3}


NameError: name 'S' is not defined

In [ ]:
# wap which will take string as input from user and count number of unique character  in that string
input_string = input("Enter a string: ")
unique_characters = set(input_string)
count = len(unique_characters)
print(f"The number of unique characters in the string is: {count}")

Enter a string: hello my name is robin
The number of unique characters in the string is: 13


In [ ]:
str1 = "hello my name is robin my is "
lst = str1.split()
str2=""
for i in lst:
  if i not in str2:
    str2 =str2+" "+i
print(str2)

 hello my name is robin


In [ ]:
set1 = {1,2,3,4,5,6,7}
set2 = {3,4,5,8,7,9,10}
a = set1 | set2#| this is for union
print(a)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


In [ ]:
set1 = {1,2,3,4,5,6,7}
set2 = {3,4,5,8,7,9,10}
a = set1.union(set2)
print(a)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


In [ ]:
set1 = {1,2,3,4,5,6,7}
set2 = {3,4,5,8,7,9,10}
a = set1.intersection(set2)
print(a)

{3, 4, 5, 7}


In [ ]:
set1 = {1,2,3,4,5,6,7}
set2 = {3,4,5,8,7,9,10}
a = set1 & set2 #& intersection ke liye use hota hai
print(a)

{3, 4, 5, 7}


In [ ]:
set1 = {1,2,3,4,5,6,7}
set2 = {3,4,5,8,7,9,10}
a = set1 - set2 # - diffrence ke liye use hota hai matlab woh element jo set1 mein hai set2 mein nhi
print(a)

{1, 2, 6}


In [ ]:
set1 = {1,2,3,4,5,6,7}
set2 = {3,4,5,8,7,9,10}
a = set1 ^ set2 # - diffrence ke liye use hota hai
print(a)

{1, 2, 6, 8, 9, 10}


In [ ]:
set1 =frozenset((1,2,3,4,5,6,7))
set2 =frozenset((3,4,5,8,7,9,1))
print(set1,"\n",set2)

frozenset({1, 2, 3, 4, 5, 6, 7}) 
 frozenset({1, 3, 4, 5, 7, 8, 9})


# Dictonary
1. immutable hota hai
2. only unique keys store krta hai
3. mix data type

In [ ]:
my_dict1 = {}
my_dict2 = {1:'abx',2: 'xyz'}
my_dict3 = {"name":"satish", "age": 20}
print(my_dict1,my_dict2,my_dict3)

{} {1: 'abx', 2: 'xyz'} {'name': 'satish', 'age': 20}


In [ ]:
# list of list
d1 = dict([[1,'abc'],[2,'code'],[3,'defr']])
print(d1)
#list of tuple
d2 = dict([('a',1),('b',2),('c',3)])
print(d2)
#list of set
d3 = dict([{'hii',23},{'byy',56},{'hello',55}])
print(d3)
#tuple of list
d4 = dict((['man',90],['woman',80]))
print(d4)

{1: 'abc', 2: 'code', 3: 'defr'}
{'a': 1, 'b': 2, 'c': 3}
{'hii': 23, 56: 'byy', 'hello': 55}
{'man': 90, 'woman': 80}


dict access

In [ ]:
my_dict = {'name':'robin','age':20,'add':'guntur'}
print(my_dict['add'])

guntur


In [ ]:
my_dict = {'name':'robin','age':20,'add':'guntur'}
print(my_dict.get('age'))

20


In [ ]:
my_dict = {'name':'robin','age':20,'add':'guntur'}
my_dict['name1'] = 'raju'#update krna
print(my_dict)

{'name': 'robin', 'age': 20, 'add': 'guntur', 'name1': 'raju'}


In [ ]:
my_dict = {'name':'robin','age':20,'add':'guntur'}
print(my_dict.pop('age')) # element delete krne ke liya
print(my_dict)

20
{'name': 'robin', 'add': 'guntur'}


In [ ]:
my_dict = {'name':'robin','age':20,'add':'guntur'}
a = my_dict.popitem() # delete krne ke liye yeh last element delete krta hai
print(a)
print(my_dict)

('add', 'guntur')
{'name': 'robin', 'age': 20}


In [ ]:
x = [3,4,5,6,7,8]
y = x
y[2] = 9
print(x,y)

[3, 4, 9, 6, 7, 8] [3, 4, 9, 6, 7, 8]


In [ ]:
x  = [ 4,8,9,2,7,5,99,]
y = x
y[3]=7777
print(x,y)

[4, 8, 9, 7777, 7, 5, 99] [4, 8, 9, 7777, 7, 5, 99]


In [ ]:
x  = [ 4,8,9,2,7,5,99,]
y = x.copy()
y[3]=7777
print(x,y)

[4, 8, 9, 2, 7, 5, 99] [4, 8, 9, 7777, 7, 5, 99]


In [ ]:
subject = {2:4,3:9,5:10}
print(subject.items())
print(subject.keys())
print(subject.values())

dict_items([(2, 4), (3, 9), (5, 10)])
dict_keys([2, 3, 5])
dict_values([4, 9, 10])


In [ ]:
subject = {2:4,3:9,5:10}
for k in subject.keys():
  print(subject[k],end = ',')

4,9,10,

In [ ]:
d = {3:5,4:7,8:10,9:11,12:35}# odd values mein 5 plus karo
for k in d.keys():
  if k%2 !=0:
    d[k] +=5
print(d)

{3: 10, 4: 7, 8: 10, 9: 16, 12: 35}


In [ ]:
d = {3:[1,2,3,4,6],4:[7,8,9,10],5:[2,3,4,7,8],6:[1,3,5,2]}
#count krna hai list mein present odd numbers ko
for key in d:
  odd_count = 0
  for number in d[key]:
    if number % 2 != 0:
      odd_count += 1
  d[key] = odd_count
print(d)

{3: 2, 4: 2, 5: 2, 6: 3}


In [ ]:
lst = (3,5,7,2,3,5,8,7,9,5,10,5,3)
#o/p ana chaiye ki number kitni baar repeat hua hai aur nayi dict banana hai
my_dict = {}
for item in lst:
  if item in my_dict:
    my_dict[item] +=1
  else:
    my_dict[item] = 1
print(my_dict)

{3: 3, 5: 4, 7: 2, 2: 1, 8: 1, 9: 1, 10: 1}


In [ ]:
d = {3:5,4:7,5:25,8:30,15:8}
x = max(d.keys())
print(x,d[x])
k1,v1 = 3,5
for k,v in d.items():
  if v>v1:
    k1=k
    v1=v
print(k1,v1)

15 8
8 30


In [ ]:
# dict comprihansion
d = {'a':1,'b':2,'c':3,'d':4}
new_dict = {k:v for k,v in d.items() if v>2}
print(new_dict)

{'c': 3, 'd': 4}


In [ ]:
# dict comprihansion
d = {'a':1,'b':2,'c':3,'d':4}
new_dict = {k+"c":v*2 for k,v in d.items() if v>2}
print(new_dict)

{'cc': 6, 'dc': 8}


In [ ]:
subject = {2:[42,3,4,56],3:[9,1,2,3,4],4:[16,2,3],5:[25,10,2]}
for k in subject.keys():
  subject[k]=sum(subject[k])
print(subject)

{2: 105, 3: 19, 4: 21, 5: 37}


In [ ]:
subject = {2:[42,3,4,56],3:[9,1,2,3,4],4:[16,2,3],5:[25,10,2]}
for key in subject:
  for i in range(len(subject[key])):
    subject[key][i] += 1
print(subject)

{2: [43, 4, 5, 57], 3: [10, 2, 3, 4, 5], 4: [17, 3, 4], 5: [26, 11, 3]}


In [ ]:
subject = {2:[42,3,4,56],3:[9,1,2,3,4],4:[16,2,3],5:[25,10,2]}
for k,v in subject.items():
  subject[k]=[i+1 for i in v]
print(subject)

{2: [43, 4, 5, 57], 3: [10, 2, 3, 4, 5], 4: [17, 3, 4], 5: [26, 11, 3]}


#FUNCTION

In [ ]:
def fact(n):
  temp = 1
  for i in range(1,n+1):
    temp*=i
  return temp
n = int(input("enter the n = "))
r =  int(input("enter the r = "))
n_fact=fact(n)
r_fact=fact(r)
n_min_r=fact(n-r)
ans=

In [ ]:
def print_info(name,id,age):
  print(name+id)
  print("age is ",age)
print_info("robin","rp5607",20)

robinrp5607
age is  20


In [ ]:
def prime(lst):
  prime_sum = 0
  for num in lst:
    if num > 1:
      is_prime = True
      for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
          is_prime = False
          break
      if is_prime:
        prime_sum += num
  return prime_sum

lst = [3, 2, 4, 5, 3, 7, 8, 9, 4, 3, 2, 1]
total_prime_sum = prime(lst)
print("The sum of prime numbers in the list is: ",{total_prime_sum})

In [ ]:
def check_prime(n):
  if n == 2 or n == 3 or n==5 or n==7:
    return True
  else :
    return False
lst = [3, 2, 4, 5, 3, 7, 8, 9, 4, 3, 2, 1]
ans = 0
for i in lst:
  if check_prime(i):
    ans+=i
print(ans)

25


#lambda function
. also known as anonimous function it has no name


In [ ]:
x = lambda n:n*n*n
print(type(x))
print(x(3))

<class 'function'>
27


In [ ]:
# take 3 number as  input from user and calculate average of the numbers
a = int(input("enter the number = "))
b = int(input("enter the number = "))
c = int(input("enter the number = "))
average = lambda x,y,z :(x+y+z)/3
print("average of numbers = ",average(a,b,c))

enter the number = 1
enter the number = 2
enter the number = 3
average of numbers =  2.0


In [ ]:
# take string as input from user and check string is start from a or not
y = lambda x:x[0] == 'a'
y('hello')

False

In [ ]:
x = lambda n: "even" if n%2==0 else "odd"
print(x(5))

odd


In [ ]:
# take input from user and check number is prime or not using lambda function
is_prime = lambda n: n > 1 and all(n % i != 0 for i in range(2, int(n**0.5) + 1))
num = int(input("Enter a number: "))
if is_prime(num):
  print(f"{num} is a prime number")
else:
  print(f"{num} is not a prime number")

Enter a number: 55
55 is not a prime number


True


map function

In [ ]:
lst = [1,2,3,4,5,6,7,8,9]
x = list(map(lambda x:x**2,lst))
print(x)

[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
lst = ['hello','coding','rich']
x = list(map(lambda x:x.upper(),lst))
print(x)

['HELLO', 'CODING', 'RICH']


fillter ()

* a fillter operation applies to all the function to all the element of a sequesnce . a sequence of those element for which function returns true is returned


In [ ]:
lst = [1,2,3,4,5,6,7,8,9]
var = list(filter(lambda x:x>4,lst))
print(var)

[5, 6, 7, 8, 9]


In [ ]:
# ek list of string lena hai aur unmein se jo a se start hai unko consider krna hai using filter
lst = ['hello','apple','appe','ausu']
a = list(filter(lambda x:x[0]=='a',lst))
print(a)

['apple', 'appe', 'ausu']


reduce

In [ ]:
from functools import reduce
l = [2,3,4,5,6,7,8,9]
y = reduce(lambda x,y:x+y,l)
print(y)

44


exception handling
try except

In [ ]:
try:
  lst = [12,3,14,5,6]
  print(lst[10])
except:
  print("index is out of range please enter the valid index")

index is out of range please enter the valid index


In [ ]:
#multiple except
try:
  lst = [12,12,13,13,14,15,16,17,180]
  print(lst[10])
  print(b)
  print(5/0)
except IndexError:
  print("enter valid index number ")
except NameEror:
  print("variable is not define")
except DivisionError:
  print("cannot divide by zero")

enter valid index number 


In [ ]:
# find the kth max and min element of an array
num = (5,5,8,7,9,2,4,6,58,77)
sorted_num = sorted(num)
print(sorted_num)


[2, 4, 5, 5, 6, 7, 8, 9, 58, 77]


In [ ]:
# Find max and min of an array without using max() or min() using sorting
my_list = [5, 5, 8, 7, 9, 2, 4, 6, 58, 77]


The minimum element is: 2
The maximum element is: 77


In [ ]:
my_list = [5, 5, 8, 7, 9, 2, 4, 6, 58, 77]
if not my_list:
  print("The list is empty.")
else:
  maximum = my_list[0]
  minimum = my_list[0]
  for number in my_list[1:]:
    if number > maximum:
      maximum = number
    if number < minimum:
      minimum = number

  print(f"The minimum element is: {minimum}")
  print(f"The maximum element is: {maximum}")

The minimum element is: 2
The maximum element is: 77


In [ ]:
# Find the kth max and min element of an array using sorting
my_list = [5, 5, 8, 7, 9, 2, 4, 6, 58, 77]
k = 3 # Example: Find the 3rd maximum and minimum

if not my_list:
  print("The list is empty.")
elif k <= 0 or k > len(my_list):
  print(f"Invalid value for k: {k}. k must be between 1 and {len(my_list)}")
else:
  sorted_list = sorted(my_list)

  # Find the kth minimum element
  kth_minimum = sorted_list[k - 1]

  # Find the kth maximum element
  kth_maximum = sorted_list[-k]

  print(f"The {k}th minimum element is: {kth_minimum}")
  print(f"The {k}th maximum element is: {kth_maximum}")

The 3th minimum element is: 5
The 3th maximum element is: 9


In [ ]:
import pandas as pd
import numpy as np
s = pd.Series([1,2,3], index = ['a','b','x'])
print(s.values)

[1 2 3]


In [ ]:
s.name ='myseries'
print(s.name)

myseries


In [ ]:
print(s.size)

3


In [ ]:
print(s.shape)

(3,)


In [ ]:
#create a series for with unique  values
marks_series = pd.Series([90,85,78,92,88])
print(marks_series.is_unique)

True


In [ ]:
s_with_nan = pd.Series([1,2,None,4])
print(s_with_nan.isnull())
print(s_with_nan.notnull())

0    False
1    False
2     True
3    False
dtype: bool
0     True
1     True
2    False
3     True
dtype: bool


In [ ]:
data = pd.Series([10,20,30,40,50],index=['a','b','c','d','e'])
print(data)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [ ]:
print(data['c'])

30


In [ ]:
print(data.loc['c'])#name se access ke liye

30


In [ ]:
print(data.iloc[2])#index location se access krne ke liye

30


In [ ]:
print(data[['a','c','e']])#using label indexing

a    10
c    30
e    50
dtype: int64


In [ ]:
#using integer position or fancy indexing
print(data [[0,2,4]])
print()
print(data[[1,3]])
print()
print(data[[1,2,3]])

a    10
c    30
e    50
dtype: int64

b    20
d    40
dtype: int64

b    20
c    30
d    40
dtype: int64


/tmp/ipython-input-23-955853564.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(data [[0,2,4]])
/tmp/ipython-input-23-955853564.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(data[[1,3]])
/tmp/ipython-input-23-955853564.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(data[[1,2,3]])


##slicing
#it allows you to extract a subset of the series

In [ ]:
data = pd.Series([10,20,30,40,50],index = ['a','b','c','d','e'])
print(data)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [ ]:
print(data['b':'d'])

b    20
c    30
d    40
dtype: int64


In [ ]:
print(data[1:4])
print()
print(data[2:5])
print()
print(data[::-1])
print()
print(data[0::2])

b    20
c    30
d    40
dtype: int64

c    30
d    40
e    50
dtype: int64

e    50
d    40
c    30
b    20
a    10
dtype: int64

a    10
c    30
e    50
dtype: int64


BOOLEAN SLICING
### CONDITION BASED SLICING

In [ ]:
#get element grater than 25
print(data[data > 25])
print()
##get element less than 25
print(data[data < 25])
print()
#get element more than equal to 20
print(data[data >= 20])
print()
#get element more than equal to 20
print(data[data <= 20])
print()

c    30
d    40
e    50
dtype: int64

a    10
b    20
dtype: int64

b    20
c    30
d    40
e    50
dtype: int64

a    10
b    20
dtype: int64



In [ ]:
x = pd.Series(np.arange(1,25))
print(x)
#select all the even numbers
# all the odd numbers
#number divisible by both 2,4

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
23    24
dtype: int64


In [ ]:
# Select all the even numbers
even_numbers = x[x % 2 == 0]
print("Even numbers:")
print(even_numbers)

Even numbers:
1      2
3      4
5      6
7      8
9     10
11    12
13    14
15    16
17    18
19    20
21    22
23    24
dtype: int64


In [ ]:
# Select all the odd numbers
odd_numbers = x[x % 2 != 0]
print("Odd numbers:")
print(odd_numbers)

Odd numbers:
0      1
2      3
4      5
6      7
8      9
10    11
12    13
14    15
16    17
18    19
20    21
22    23
dtype: int64


In [ ]:
# Select numbers divisible by both 2 and 4 (which is equivalent to divisible by 4)
divisible_by_2_4 = x[(x % 2 == 0)&(x % 4 == 0)]
print("Numbers divisible by both 2 and 4:")
print(divisible_by_2_4)

Numbers divisible by both 2 and 4:
3      4
7      8
11    12
15    16
19    20
23    24
dtype: int64


MODIFYING ELEMENT


In [ ]:
data = pd.Series([10,20,40,30,50],index = ['a','b','c','d','e'])
print(data)

a    10
b    20
c    40
d    30
e    50
dtype: int64


In [ ]:
data['a'] = 15
print(data)
print()
data[1:3]=[25,35]
print(data)

a    15
b    20
c    40
d    30
e    50
dtype: int64

a    15
b    25
c    35
d    30
e    50
dtype: int64


In [ ]:
#series create karo jo divisble by 3&5
s1 = pd.Series(np.arange(5,50))
s2 = s1[(s1%3 == 0)&(s1%5 == 0)]
print(s2)

10    15
25    30
40    45
dtype: int64


In [ ]:
s1 = pd.Series([i for i in range(5,50) if i%3==0 or i%5==0])
print(s1)

0      5
1      6
2      9
3     10
4     12
5     15
6     18
7     20
8     21
9     24
10    25
11    27
12    30
13    33
14    35
15    36
16    39
17    40
18    42
19    45
20    48
dtype: int64


In [ ]:
#even numbers ko +5 karo
#series create karo jo divisble by 3&5
s1 = pd.Series(np.arange(3,50))
s2 = s1[(s1%2==0)]
s2+=5
print(s2)

1      9
3     11
5     13
7     15
9     17
11    19
13    21
15    23
17    25
19    27
21    29
23    31
25    33
27    35
29    37
31    39
33    41
35    43
37    45
39    47
41    49
43    51
45    53
dtype: int64


In [ ]:
#create a pandas series
data = pd.Series([1,2,3,4,5,6,7,8,9,10])
sq_values =[]
for value in data :
  sq_values.append(value**2)
sq_series = pd.Series(sq_values)
print(sq_series)

0      1
1      4
2      9
3     16
4     25
5     36
6     49
7     64
8     81
9    100
dtype: int64


In [ ]:
data_sample = [[50,60,70],
               [70,80,90],
               [100,110,120]]
data1 = pd.DataFrame(data_sample, columns = ['python','c','html'])
data1

python    c  html
0      50   60    70
1      70   80    90
2     100  110   120

In [ ]:
#usnig dict
data_dict = {
    'col1':['name1','name2','name3','name4','name5'],
    'col2':[100,90,120,78,99],
    'col3':[100,90,120,78,99],
    'col4':[100,90,120,78,99],
    'col5':[100,90,120,78,99],

}
students = pd.DataFrame(data_dict)
students

col1  col2  col3  col4  col5
0  name1   100   100   100   100
1  name2    90    90    90    90
2  name3   120   120   120   120
3  name4    78    78    78    78
4  name5    99    99    99    99

In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
austin = pd.read_csv('/content/data set 1.csv')
print(austin)

            Date  TempHighF  TempAvgF  TempLowF DewPointHighF DewPointAvgF  \
0     21-12-2013         74        60        45            67           49   
1     22-12-2013         56        48        39            43           36   
2     23-12-2013         58        45        32            31           27   
3     24-12-2013         61        46        31            36           28   
4     25-12-2013         58        50        41            44           40   
...          ...        ...       ...       ...           ...          ...   
1314  27-07-2017        103        89        75            71           67   
1315  28-07-2017        105        91        76            71           64   
1316  29-07-2017        107        92        77            72           64   
1317  30-07-2017        106        93        79            70           68   
1318  31-07-2017         99        88        77            66           61   

     DewPointLowF HumidityHighPercent HumidityAvgPercent Humidi

In [5]:
 titanic = pd.read_csv("/content/titanic data set.csv")

In [6]:
titanic.info()
titanic

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Survived     418 non-null    int64  
 2   Pclass       418 non-null    int64  
 3   Name         418 non-null    object 
 4   Sex          418 non-null    object 
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64  
 7   Parch        418 non-null    int64  
 8   Ticket       418 non-null    object 
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object 
 11  Embarked     418 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB


PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                       Myles, Mr. Thomas Francis    male  62.0      0      0   
3                                Wirz, Mr. Albert    male  27.0      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
..                                            ...     ...   ...    ...    ...   
413                            Spector, Mr. Woolf    male   NaN      0      0   
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0   
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0   
416                           Ware, Mr. Frederick    male   NaN      0      0   
417                      Peter, Master. Michael J    male   NaN      1      1   

                 Ticket      Fare Cabin Embarked  
0                330911    7.8292   NaN        Q  
1                363272    7.0000   NaN        S  
2                240276    9.6875   NaN        Q  
3                315154    8.6625   NaN        S  
4               3101298   12.2875   NaN        S  
..                  ...       ...   ...      ...  
413           A.5. 3236    8.0500   NaN        S  
414            PC 17758  108.9000  C105        C  
415  SOTON/O.Q. 3101262    7.2500   NaN        S  
416              359309    8.0500   NaN        S  
417                2668   22.3583   NaN        C  

[418 rows x 12 columns]

In [ ]:
titanic.isnull()

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False   
1          False     False   False  False  False  False  False  False   False   
2          False     False   False  False  False  False  False  False   False   
3          False     False   False  False  False  False  False  False   False   
4          False     False   False  False  False  False  False  False   False   
..           ...       ...     ...    ...    ...    ...    ...    ...     ...   
413        False     False   False  False  False   True  False  False   False   
414        False     False   False  False  False  False  False  False   False   
415        False     False   False  False  False  False  False  False   False   
416        False     False   False  False  False   True  False  False   False   
417        False     False   False  False  False   True  False  False   False   

      Fare  Cabin  Embarked  
0    False   True     False  
1    False   True     False  
2    False   True     False  
3    False   True     False  
4    False   True     False  
..     ...    ...       ...  
413  False   True     False  
414  False  False     False  
415  False   True     False  
416  False   True     False  
417  False   True     False  

[418 rows x 12 columns]

In [ ]:
print(titanic.shape)
print(austin.shape)

(418, 12)
(1319, 21)


In [ ]:
print(titanic.dtypes)
print("=========================================")
print(austin.dtypes)


PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object
Date                          object
TempHighF                      int64
TempAvgF                       int64
TempLowF                       int64
DewPointHighF                 object
DewPointAvgF                  object
DewPointLowF                  object
HumidityHighPercent           object
HumidityAvgPercent            object
HumidityLowPercent            object
SeaLevelPressureHighInches    object
SeaLevelPressureAvgInches     object
SeaLevelPressureLowInches     object
VisibilityHighMiles           object
VisibilityAvgMiles            object
VisibilityLowMiles            object
WindHighMPH                   object
WindAvgMPH                    object
WindGustMPH                   object
Precipi

In [ ]:

print(titanic.index)
print(austin.index)

RangeIndex(start=0, stop=418, step=1)
RangeIndex(start=0, stop=1319, step=1)


In [ ]:
print(titanic.columns)
print(austin.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')
Index(['Date', 'TempHighF', 'TempAvgF', 'TempLowF', 'DewPointHighF',
       'DewPointAvgF', 'DewPointLowF', 'HumidityHighPercent',
       'HumidityAvgPercent', 'HumidityLowPercent',
       'SeaLevelPressureHighInches', 'SeaLevelPressureAvgInches',
       'SeaLevelPressureLowInches', 'VisibilityHighMiles',
       'VisibilityAvgMiles', 'VisibilityLowMiles', 'WindHighMPH', 'WindAvgMPH',
       'WindGustMPH', 'PrecipitationSumInches', 'Events'],
      dtype='object')


In [ ]:
print(titanic.values)

[[892 0 3 ... 7.8292 nan 'Q']
 [893 1 3 ... 7.0 nan 'S']
 [894 0 2 ... 9.6875 nan 'Q']
 ...
 [1307 0 3 ... 7.25 nan 'S']
 [1308 0 3 ... 8.05 nan 'S']
 [1309 0 3 ... 22.3583 nan 'C']]


In [ ]:
titanic.head(7)#by default it give top 5 row

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   
5          897         0       3   
6          898         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
5                    Svensson, Mr. Johan Cervin    male  14.0      0      0   
6                          Connolly, Miss. Kate  female  30.0      0      0   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S  
5     7538   9.2250   NaN        S  
6   330972   7.6292   NaN        Q

In [ ]:
titanic.tail()

PassengerId  Survived  Pclass                          Name     Sex  \
413         1305         0       3            Spector, Mr. Woolf    male   
414         1306         1       1  Oliva y Ocana, Dona. Fermina  female   
415         1307         0       3  Saether, Mr. Simon Sivertsen    male   
416         1308         0       3           Ware, Mr. Frederick    male   
417         1309         0       3      Peter, Master. Michael J    male   

      Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
413   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  39.0      0      0            PC 17758  108.9000  C105        C  
415  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416   NaN      0      0              359309    8.0500   NaN        S  
417   NaN      1      1                2668   22.3583   NaN        C

In [ ]:
austin.head()


Date  TempHighF  TempAvgF  TempLowF DewPointHighF DewPointAvgF  \
0  21-12-2013         74        60        45            67           49   
1  22-12-2013         56        48        39            43           36   
2  23-12-2013         58        45        32            31           27   
3  24-12-2013         61        46        31            36           28   
4  25-12-2013         58        50        41            44           40   

  DewPointLowF HumidityHighPercent HumidityAvgPercent HumidityLowPercent  ...  \
0           43                  93                 75                 57  ...   
1           28                  93                 68                 43  ...   
2           23                  76                 52                 27  ...   
3           21                  89                 56                 22  ...   
4           36                  86                 71                 56  ...   

  SeaLevelPressureAvgInches SeaLevelPressureLowInches VisibilityHighMiles  \
0                     29.68                     29.59                  10   
1                     30.13                     29.87                  10   
2                     30.49                     30.41                  10   
3                     30.45                      30.3                  10   
4                     30.33                     30.27                  10   

  VisibilityAvgMiles VisibilityLowMiles WindHighMPH WindAvgMPH WindGustMPH  \
0                  7                  2          20          4          31   
1                 10                  5          16          6          25   
2                 10                 10           8          3          12   
3                 10                  7          12          4          20   
4                 10                  7          10          2          16   

  PrecipitationSumInches               Events  
0                   0.46  Rain , Thunderstorm  
1                      0                       
2                      0                       
3                      0                       
4                      T                       

[5 rows x 21 columns]

In [ ]:
austin.tail()

Date  TempHighF  TempAvgF  TempLowF DewPointHighF DewPointAvgF  \
1314  27-07-2017        103        89        75            71           67   
1315  28-07-2017        105        91        76            71           64   
1316  29-07-2017        107        92        77            72           64   
1317  30-07-2017        106        93        79            70           68   
1318  31-07-2017         99        88        77            66           61   

     DewPointLowF HumidityHighPercent HumidityAvgPercent HumidityLowPercent  \
1314           61                  82                 54                 25   
1315           55                  87                 54                 20   
1316           55                  82                 51                 19   
1317           63                  69                 48                 27   
1318           54                  64                 43                 22   

      ... SeaLevelPressureAvgInches SeaLevelPressureLowInches  \
1314  ...                     29.97                     29.88   
1315  ...                      29.9                     29.81   
1316  ...                     29.86                     29.79   
1317  ...                     29.91                     29.87   
1318  ...                     29.97                     29.91   

     VisibilityHighMiles VisibilityAvgMiles VisibilityLowMiles WindHighMPH  \
1314                  10                 10                 10          12   
1315                  10                 10                 10          14   
1316                  10                 10                 10          12   
1317                  10                 10                 10          13   
1318                  10                 10                 10          12   

     WindAvgMPH WindGustMPH PrecipitationSumInches Events  
1314          5          21                      0         
1315          5          20                      0         
1316          4          17                      0         
1317          4          20                      0         
1318          4          20                      0         

[5 rows x 21 columns]

In [ ]:
titanic.sample(10)#by default it give one randonm value

PassengerId  Survived  Pclass  \
127         1019         1       3   
355         1247         0       1   
280         1172         1       3   
80           972         0       3   
179         1071         1       1   
412         1304         1       3   
308         1200         0       1   
360         1252         0       3   
261         1153         0       3   
167         1059         0       3   

                                                  Name     Sex   Age  SibSp  \
127                                McCoy, Miss. Alicia  female   NaN      2   
355                           Julian, Mr. Henry Forbes    male  50.0      0   
280                             Oreskovic, Miss. Jelka  female  23.0      0   
80                                Boulos, Master. Akar    male   6.0      1   
179  Compton, Mrs. Alexander Taylor (Mary Eliza Ing...  female  64.0      0   
412                     Henriksson, Miss. Jenny Lovisa  female  28.0      0   
308                         Hays, Mr. Charles Melville    male  55.0      1   
360                        Sage, Master. William Henry    male  14.5      8   
261                      Nilsson, Mr. August Ferdinand    male  21.0      0   
167                            Ford, Mr. Edward Watson    male  18.0      2   

     Parch      Ticket     Fare Cabin Embarked  
127      0      367226  23.2500   NaN        Q  
355      0      113044  26.0000   E60        S  
280      0      315085   8.6625   NaN        S  
80       1        2678  15.2458   NaN        C  
179      2    PC 17756  83.1583   E45        C  
412      0      347086   7.7750   NaN        S  
308      1       12749  93.5000   B69        S  
360      2    CA. 2343  69.5500   NaN        S  
261      0      350410   7.8542   NaN        S  
167      2  W./C. 6608  34.3750   NaN        S

In [ ]:
titanic.info()# for tracking memory usage

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Survived     418 non-null    int64  
 2   Pclass       418 non-null    int64  
 3   Name         418 non-null    object 
 4   Sex          418 non-null    object 
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64  
 7   Parch        418 non-null    int64  
 8   Ticket       418 non-null    object 
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object 
 11  Embarked     418 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB


In [ ]:
titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   418.000000  418.000000  418.000000  332.000000  418.000000   
mean   1100.500000    0.363636    2.265550   30.272590    0.447368   
std     120.810458    0.481622    0.841838   14.181209    0.896760   
min     892.000000    0.000000    1.000000    0.170000    0.000000   
25%     996.250000    0.000000    1.000000   21.000000    0.000000   
50%    1100.500000    0.000000    3.000000   27.000000    0.000000   
75%    1204.750000    1.000000    3.000000   39.000000    1.000000   
max    1309.000000    1.000000    3.000000   76.000000    8.000000   

            Parch        Fare  
count  418.000000  417.000000  
mean     0.392344   35.627188  
std      0.981429   55.907576  
min      0.000000    0.000000  
25%      0.000000    7.895800  
50%      0.000000   14.454200  
75%      0.000000   31.500000  
max      9.000000  512.329200

In [ ]:
austin.describe()

TempHighF     TempAvgF     TempLowF
count  1319.000000  1319.000000  1319.000000
mean     80.862775    70.642911    59.902957
std      14.766523    14.045904    14.190648
min      32.000000    29.000000    19.000000
25%      72.000000    62.000000    49.000000
50%      83.000000    73.000000    63.000000
75%      92.000000    83.000000    73.000000
max     107.000000    93.000000    81.000000

In [ ]:
titanic.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
titanic.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
413    False
414    False
415    False
416    False
417    False
Length: 418, dtype: bool

In [ ]:
titanic.duplicated().sum()

np.int64(0)

In [ ]:
austin.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
1314    False
1315    False
1316    False
1317    False
1318    False
Length: 1319, dtype: bool

In [ ]:
austin.duplicated().sum()

np.int64(0)

In [11]:
#usnig dict
data_dict = {
    'col1':['name1','name2','name3','name4','name5'],
    'col2':[100,90,120,78,99],
    'col3':[100,90,120,78,99],
    'col4':[100,90,120,78,99],
    'col5':[100,90,120,78,99],

}
students = pd.DataFrame(data_dict)
students

col1  col2  col3  col4  col5
0  name1   100   100   100   100
1  name2    90    90    90    90
2  name3   120   120   120   120
3  name4    78    78    78    78
4  name5    99    99    99    99

In [12]:
students.rename(columns ={'col2':'python','col3':'c++'})

col1  python  c++  col4  col5
0  name1     100  100   100   100
1  name2      90   90    90    90
2  name3     120  120   120   120
3  name4      78   78    78    78
4  name5      99   99    99    99

In [13]:
students.rename(columns ={'col2':'python','col3':'c++'},inplace  =True)
students

col1  python  c++  col4  col5
0  name1     100  100   100   100
1  name2      90   90    90    90
2  name3     120  120   120   120
3  name4      78   78    78    78
4  name5      99   99    99    99

In [14]:
students.sum()

col1      name1name2name3name4name5
python                          487
c++                             487
col4                            487
col5                            487
dtype: object

In [15]:
students.mean(axis=1)

TypeError: can only concatenate str (not "int") to str

In [ ]:
titanic['Name']

0                                  Kelly, Mr. James
1                  Wilkes, Mrs. James (Ellen Needs)
2                         Myles, Mr. Thomas Francis
3                                  Wirz, Mr. Albert
4      Hirvonen, Mrs. Alexander (Helga E Lindqvist)
                           ...                     
413                              Spector, Mr. Woolf
414                    Oliva y Ocana, Dona. Fermina
415                    Saether, Mr. Simon Sivertsen
416                             Ware, Mr. Frederick
417                        Peter, Master. Michael J
Name: Name, Length: 418, dtype: object

In [ ]:
austin['Date']

0       21-12-2013
1       22-12-2013
2       23-12-2013
3       24-12-2013
4       25-12-2013
           ...    
1314    27-07-2017
1315    28-07-2017
1316    29-07-2017
1317    30-07-2017
1318    31-07-2017
Name: Date, Length: 1319, dtype: object

In [ ]:
titanic.iloc[5]

PassengerId                           897
Survived                                0
Pclass                                  3
Name           Svensson, Mr. Johan Cervin
Sex                                  male
Age                                  14.0
SibSp                                   0
Parch                                   0
Ticket                               7538
Fare                                9.225
Cabin                                 NaN
Embarked                                S
Name: 5, dtype: object

In [ ]:
austin.iloc[5]

Date                          26-12-2013
TempHighF                             57
TempAvgF                              48
TempLowF                              39
DewPointHighF                         39
DewPointAvgF                          36
DewPointLowF                          33
HumidityHighPercent                   79
HumidityAvgPercent                    63
HumidityLowPercent                    47
SeaLevelPressureHighInches         30.47
SeaLevelPressureAvgInches           30.4
SeaLevelPressureLowInches          30.34
VisibilityHighMiles                   10
VisibilityAvgMiles                     9
VisibilityLowMiles                     7
WindHighMPH                           12
WindAvgMPH                             3
WindGustMPH                           17
PrecipitationSumInches                 0
Events                                  
Name: 5, dtype: object

In [ ]:
titanic.iloc[5:26:3]

PassengerId  Survived  Pclass  \
5           897         0       3   
8           900         1       3   
11          903         0       1   
14          906         1       1   
17          909         0       3   
20          912         0       1   
23          915         0       1   

                                                 Name     Sex   Age  SibSp  \
5                          Svensson, Mr. Johan Cervin    male  14.0      0   
8           Abrahim, Mrs. Joseph (Sophie Halaut Easu)  female  18.0      0   
11                         Jones, Mr. Charles Cresson    male  46.0      0   
14  Chaffee, Mrs. Herbert Fuller (Carrie Constance...  female  47.0      1   
17                                  Assaf, Mr. Gerios    male  21.0      0   
20                             Rothschild, Mr. Martin    male  55.0      1   
23                    Williams, Mr. Richard Norris II    male  21.0      0   

    Parch       Ticket     Fare Cabin Embarked  
5       0         7538   9.2250   NaN        S  
8       0         2657   7.2292   NaN        C  
11      0          694  26.0000   NaN        S  
14      0  W.E.P. 5734  61.1750   E31        S  
17      0         2692   7.2250   NaN        C  
20      0     PC 17603  59.4000   NaN        C  
23      1     PC 17597  61.3792   NaN        C

In [ ]:
#wap which subtract the mean of each row from a matrix (create a matrix of random element)
import numpy as np

In [ ]:
a = np.array([[3,4],[6,7]])
print(a)
print("=============")
row_mean = np.mean(a, axis=1)
print(row_mean)
print("=============")
result = a-row_mean
print(result)

[[3 4]
 [6 7]]
[3.5 6.5]
[[-0.5 -2.5]
 [ 2.5  0.5]]


In [ ]:
'''Write a python program to count the number of elements in 2D array.
Test case: Input: np.array([1, 2])
 Expected Output: 2
'''
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = (arr1.size)
print('size is = ',arr2)


size is =  6


In [ ]:
'''Write a python program to replace multiples of 3 or 5 as 0 in the given
array.
Input: arr=[1 2 3 4 5 6 7 9]
Expected Output: [1 2 0 4 0 0 7 0]
'''
arr = [1, 2, 3, 4, 5, 6, 7, 9]
print("Original array:", arr)
for i in range(len(arr)):
  if arr[i] % 3 == 0 or arr[i] % 5 == 0:
    arr[i] = 0

print("Array after replacement:", arr)

Original array: [1, 2, 3, 4, 5, 6, 7, 9]
Array after replacement: [1, 2, 0, 4, 0, 0, 7, 0]


In [ ]:
#Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a, b) as parameter to function.
#Input: a = 4 b = 4
#Expected Output:
#[[1,1,1,1],
 #[1,0,0,1],
#[1,0,0,1],
 #[1,1,1,1]]
def create_bordered_array(a, b):
  if a <= 1 or b <= 1:
    return np.ones((a, b))
  array = np.ones((a, b))
  array[1:-1, 1:-1] = 0
a = 4
b = 4
output_array = create_bordered_array(a, b)
print(f"Input: a = {a}, b = {b}")
print("Actual Output:")
print(output_array)

Input: a = 4, b = 4
Actual Output:
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [ ]:
'''Write a program which makes an array having corresponding max value out of two given arrays.
Input:
 a=np.array([6,3,1,5,8])
 b=np.array([3,2,1,7,2])
 Output: [6 3 1 7 8]
'''
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
result = np.maximum(a, b)
print("Output:", result)

Output: [6 3 1 7 8]


In [ ]:
'''Q8. Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.
Test Case: Input: a= [[0 1 2 3 4] [5 6 7 8 9]]
b= [[1 1 1 1 1] [1 1 1 1 1]]
Output:
 [[0 1 2 3 4]
[5 6 7 8 9]
[1 1 1 1 1]
 [1 1 1 1 1]]
'''
a = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
b = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
c = np.vstack((a,b))
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [1]:
'''
 Q.10  Solve the given  problem using fancy Indexing:
1. Double the array elements at given indexes
Given:
arr = np.arrange(10)
indexes = [0,3,4,9]
Expected Output: [ 0 1 2 6 8 5 6 7 8 18]
'''



'\n Q.10  Solve the given  problem using fancy Indexing:\n1. Double the array elements at given indexes\nGiven:\narr = np.arrange(10)\nindexes = [0,3,4,9]\nExpected Output: [ 0 1 2 6 8 5 6 7 8 18]\n'

In [8]:
austin.columns

Index(['Date', 'TempHighF', 'TempAvgF', 'TempLowF', 'DewPointHighF',
       'DewPointAvgF', 'DewPointLowF', 'HumidityHighPercent',
       'HumidityAvgPercent', 'HumidityLowPercent',
       'SeaLevelPressureHighInches', 'SeaLevelPressureAvgInches',
       'SeaLevelPressureLowInches', 'VisibilityHighMiles',
       'VisibilityAvgMiles', 'VisibilityLowMiles', 'WindHighMPH', 'WindAvgMPH',
       'WindGustMPH', 'PrecipitationSumInches', 'Events'],
      dtype='object')

In [9]:
austin[['Date','TempHighF', 'TempAvgF', 'TempLowF','Events']]

Date  TempHighF  TempAvgF  TempLowF               Events
0     21-12-2013         74        60        45  Rain , Thunderstorm
1     22-12-2013         56        48        39                     
2     23-12-2013         58        45        32                     
3     24-12-2013         61        46        31                     
4     25-12-2013         58        50        41                     
...          ...        ...       ...       ...                  ...
1314  27-07-2017        103        89        75                     
1315  28-07-2017        105        91        76                     
1316  29-07-2017        107        92        77                     
1317  30-07-2017        106        93        79                     
1318  31-07-2017         99        88        77                     

[1319 rows x 5 columns]

In [16]:
print(students)

    col1  python  c++  col4  col5
0  name1     100  100   100   100
1  name2      90   90    90    90
2  name3     120  120   120   120
3  name4      78   78    78    78
4  name5      99   99    99    99
